server:
  port: 9001
spring: 
  profiles: 
    active: dev
spring:
    profiles: dev
spring:
  jpa:
    hibernate:
      # Hibernate ddl auto (create, create-drop, update)
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
      # Show or not log for each sql query
      show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/db_example
    username: springuser
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
