server:
  port: 8003

spring:
  application:
    name: client-zookeeper
  cloud:
    zookeeper:
      discovery:
        register: false
        root: /spring-cloud-service
      connect-string: localhost:2181
